name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRHUSERNAME
          server-password: OSSRHPASSWORD
          gpg-private-key: ${{ secrets.SIGNINGKEY }}
          gpg-passphrase: SIGNINGPASSWORD
      - name: Maven Build
        run: ./mvnw -Prelease verify deploy
        env:
          OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
          OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}

